name: "buildenv Changes in PR"
on:
  pull_request:
    types: [ready_for_review]
    paths:
    - 'buildenv/**'
jobs:
  triggerGrinderTests:
    name: Build
    runs-on: ubuntu-16.04
    steps:
    - name: trigger single Job
      uses: stigmelling/jenkins-action@master
      with:
        jenkinsUrl: 'https://ci.adoptopenjdk.net/'
        username: 'xfxcwynlc'
        token: ${{ secrets.TOKEN }}
        job: "Grinder_Simple"
        params: '{ "JDK_VERSION": 11}'
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '2204 buildenv changed!'
            })
