name: 'Disabled Tests Linter'
on:
  pull_request:
    paths:
    - 'openjdk/excludes/*'
    - '**/playlist.xml'

jobs:
  disableTestsLinter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install python3 python3-lxml

      - name: Run exclude_parser.py on ProblemList files
        run: find ./openjdk/excludes -name "ProblemList*" | python3 ./scripts/disabled_tests/exclude_parser.py > /dev/null

      - name: Run playlist_parser.py on playlist.xml files
        run: find . -name "playlist.xml" | python3 ./scripts/disabled_tests/playlist_parser.py > /dev/null
