name: "Parse all disabled issues"
on:
  schedule:
    - cron: '0 4 * * 0'  # every Sunday, 4am UTC
  workflow_dispatch:

permissions:
  contents: read

jobs:
  parse_issues:
    runs-on: ubuntu-latest
    env:
      AQA_ISSUE_TRACKER_GITHUB_USER: ${{ github.actor }}
      AQA_ISSUE_TRACKER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Set up Python 3.8
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version: 3.8
      - name: checkout current repo
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - name: install reqs
        run: |
          pip install -r scripts/disabled_tests/requirements.txt
      - name: discover disabled tests
        run : |
          echo "::group::openjdk exclude files"
          ls -1dq openjdk/excludes/* | tee exclude_files.txt
          echo "::endgroup::"
          echo "::group::playlist files"
          find . -name "playlist.xml" -not -path "scripts" | tee playlist_files.txt
          echo "::endgroup::"
      - name: run scripts
        run: |
          echo "::group::parsing"
          cat exclude_files.txt | python scripts/disabled_tests/exclude_parser.py -v > exclude.json
          cat playlist_files.txt | python scripts/disabled_tests/playlist_parser.py -v > playlist.json
          echo "::endgroup::"
          echo "::group::merging"
          jq -s 'flatten(1)' exclude.json playlist.json > all.json
          echo "::endgroup::"
          echo "::group::status"
          cat all.json | python scripts/disabled_tests/issue_status.py -v > output.json
          echo "::endgroup::"
      - name: store artifact
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: disabled_tests
          path: output.json
          retention-days: 90
