name: "Parse all disabled issues"
on:
  schedule:
    - cron: '0 4 * * 0'  # every Sunday, 4am UTC
  workflow_dispatch:

permissions:
  contents: read

jobs:
  parse_issues:
    runs-on: ubuntu-latest
    env:
      AQA_ISSUE_TRACKER_GITHUB_USER: ${{ github.actor }}
      AQA_ISSUE_TRACKER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Set up Python 3.8
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: 3.8
      - name: checkout current repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: install reqs
        run: |
          pip install -r scripts/disabled_tests/requirements.txt
      - name: discover disabled tests
        run : |
          echo "::group::openjdk exclude files"
          ls -1dq openjdk/excludes/* | tee exclude_files.txt
          echo "::endgroup::"
          echo "::group::playlist files"
          find . -name "playlist.xml" -not -path "scripts" | tee playlist_files.txt
          echo "::endgroup::"
      - name: run scripts
        run: |
          echo "::group::parsing"
          cat exclude_files.txt | python scripts/disabled_tests/exclude_parser.py -v > exclude.json
          cat playlist_files.txt | python scripts/disabled_tests/playlist_parser.py -v > playlist.json
          echo "::endgroup::"
          echo "::group::merging"
          jq -s 'flatten(1)' exclude.json playlist.json > all.json
          echo "::endgroup::"
          echo "::group::status"
          cat all.json | python scripts/disabled_tests/issue_status.py -v > output.json
          echo "::endgroup::"
      - name: store artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: disabled_tests
          path: output.json
          retention-days: 90
